### ISSUE TITLE
Backup not Working

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#10] opened 2019-01-08 11:57 UTC
@rajesh-rajagopal 
Now you Check it .Copy file from ubunto  to Storage server

**Comment by rajesh-rajagopal** [comment] 2019-01-08 11:59
@Servernet1 
Its not fixed.. I got same error..
![image](https://user-images.githubusercontent.com/18652643/50829556-defb8f00-136a-11e9-890f-33b94f94d664.png)

**Comment by Servernet1** [comment] 2019-01-08 12:07
@rajesh-rajagopal 
Some Clarification Pls Call Elango Sir

**Comment by indykish** [comment] 2019-02-12 10:30
Duplicate of #11

**Closed by indykish** 2019-02-12 10:30 UTC
Labels: help wanted
